version: '2'

networks:
    stack:
        driver: bridge

services:
    nginx:
        image: nginx
        ports:
            - 8001:80
        volumes:
            - ./conf/nginx.conf:/etc/nginx/conf.d/plutonium.conf
            - ./src:/var/www
            - ./log:/var/log/nginx
        networks:
            - stack

    php:
        image: php:fpm
        build:
            context: .
            dockerfile: dockerfile
        volumes:
            - ./conf/php.conf:/usr/local/etc/php-fpm.d/zz-log.conf
            - ./src:/var/www
            - ./vendor:/var/lib
        networks:
            - stack

    mysql:
        image: mysql
        ports:
            - 3301:3306
        volumes:
            - ./data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: plutonium
            MYSQL_PASSWORD: plutonium
            MYSQL_DATABASE: plutonium
        networks:
            - stack
